# Generated by Django 5.2.4 on 2025-07-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role_receptionistprofile_crmcalllog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistprofile',
            name='full_name',
            field=models.CharField(default='Receptionist User', max_length=255),
        ),
    ]
