# Generated by Django 5.2.4 on 2025-07-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_receptionistprofile_full_name'),
    ]

    operations = [
    ]
