# Generated by Django 5.2.4 on 2025-07-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('drink', 'Drink')], default='lunch', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
