# Generated by Django 5.2.4 on 2025-07-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_waiter_clockinrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiterprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='waiterprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='waiterprofile',
            name='table_assigned',
            field=models.CharField(default='Unassigned', max_length=20),
        ),
    ]
