# Generated by Django 5.2.4 on 2025-07-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_waiterprofile_age_remove_waiterprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waiterprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
